CLASS LHC_ZABCR_TAXI_BOOKING_39DEF DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZabcrTaxiBooking39def
        RESULT result.
ENDCLASS.

CLASS LHC_ZABCR_TAXI_BOOKING_39DEF IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
